name: TestRJMK
favicon: null
layout_spectrum: 0.6382
typography_spectrum: 0.43222
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#bcbcb4'
    - '#3768b5'
    - '#8a846e'
  brandStrength: 0.5
  lightness: 0.3559776770416647
  saturation: 0.4163176647853106
  rhythmicContrast: 0.08685771143063903
purpose: []
